services:
  db:
    image: postgres:latest
    container_name: dbContainer
    environment:
      POSTGRES_DB: med_db     
      POSTGRES_USER: maxim         
      POSTGRES_PASSWORD: maxim 
    ports:
      - "5432:5432"                        
    volumes:
      - pg_data:/var/lib/postgresql/data   

volumes:
  pg_data: